# Questions to be handed in on Julia as a calculator


### Quick background

Read about this material here: [Julia as a calculator](http://mth229.github.io/calculator.html).

For the impatient, these questions cover the use of `julia` to replace what a calculator can do:


#### the common operations on numbers: addition, subtraction,  multiplication, division, and powers.

For the most part there is no surprise, once you learn the notations:
  `+`, `-`, `*`, `/`, and `^`. (Though you may find that copying and
  pasting minus signs will often cause an error, as only something
  that looks like a minus sign is pasted in.)

Using `IJulia`, one types the following into a cell and then presses the "run" button (or "shift-enter"):

```
2 + 2
```

The answer follows below the cell.

Here is how one does a slightly more complicated computation:

```
(2 + 3)^4/(5 + 6)
```

As with your calculator, it is very important to use parentheses as
appropriate to circumvent the usual order of operations.




#### The use of the basic families of function: trigonometric, exponential, logarithmic.

On a calculator, there are buttons used to compute various functions. In `julia`, there are *many* pre-defined functions that serve a similar role (and you will see how to define your own). Functions in `julia` have names and are called using parentheses to enclose their argument(s), as with:

```
sin(pi/4), cos(pi/3)
```

(With `IJulia`, when a cell is executed only the last command computed
is displayed, the above shows that using a comma to separate commands
on the same line can be used to get two or more commands to be
displayed.)

Most basic functions in `julia` have easy to guess names, though you
will need to learn some differences, such as `log` is for $\ln$ and
`asin` for $\sin^{-1}$.

#### the use of memory registers to remember intermediate values.

Rather than have numbered memory registers, it is *easy* to assign a name to a value. For example,

```
x = 42
```

Names can be reassigned (though at times names for functions can not be reassigned to different types of values). For assigning more than one value at once, commas can be used as with the output:

```
a,b,c = 1,2,3
```

#### Julia -- like math -- has different number types


Unlike a calculator, but just like math, `julia` has different types of
numbers: integers, rational numbers, real numbers, and complex
numbers. For the most part the distinction isn't much to worry about,
but there are times where one must, such as overflow with
integers. (One can only take the factorial of 20 with 64-bit integers,
whereas on most calculators a factorial of 69 can be taken, but
not 70.) Julia automatically assigns a type when it parses a value. a
`1` will be an integer, a `1.0` an floating point number. Rational
numbers are made by using two division symbols, `1//2`.

For many operations the type will be conserved, such as adding to
integers. For some operations, the type will be converted, such as
dividing two integer values. Mathematically, we know we can divide
some integers and still get an integer, but `julia` usually opts for
the same output for its functions (and division is also a function)
based on the type of the input, not the values of the input.


Okay, maybe that is too much. Let's get started.

### Expressions

* Compute the following value:

$$
(5/9)(-10 - 32)
$$

```
```

```
val = (5/9) * (-10 - 32)
numericq(val, 1e-3, "\\( (5/9) * (-10 - 32) \\)")
```

*  Compute the following value:

$$
9/5(100) + 32
$$

```
```


```
val = 9/5*(100) + 32
numericq(val, 1e-3, "\\( 9/5(100) + 32 \\)")
```

* Compute the following value:

$$
-4.9\cdot 10^2 + 19.6\cdot 10 + 58.8 
$$

```
```


```
val = -4.9 * 10^2 + 19.6 * 10 + 58.8 
numericq(val, 1e-3, "\\( -4.9\\cdot 10^2 + 19.6\\cdot 10 + 58.8 \\)")
```

* Compute the following value:

$$
\frac{1 + 2\cdot 3}{4 + 5^6}
$$


```
```


```
val = (1 + 2*3) / (4 + 5^6)
numericq(val, 1e-3, "\\( \\frac{1 + 2\cdot 3}{4 + 5^6} \\)")
```

## Math functions

* Compute the following value:

$$
\sqrt{0.25\cdot(1-0.25)/100}
$$

```
```


```
val = sqrt(0.25 * (1 - 0.25)/100)
numericq(val, 1e-3, "\\( \\sqrt{0.25\\cdot(1-0.25)/100} \\)")
```


* Compute the following value (here math notation and computer notation are not the same):

$$
\cos^2(\pi/3)
$$

```
```

```
val = cos(pi/3)^2
numericq(val, 1e-3, "\\( \\cos^2(\\pi/3) \\)")
```



* Compute the following value:

$$
\sin^2(\pi/3)  \cdot \cos((\pi/6)^2)
$$

```
```

```
val = sin(pi/3)^2  * cos((pi/6)^2)
numericq(val, 1e-3, "\\( \\sin^2(\\pi/3)  \\cdot \\cos((\\pi/6)^2) \\)")
```



* Compute the following value:

$$
e^{(1/2)\cdot(3 - 2.3)^2}
$$

```
```


```
val = exp((1/2)*(3 - 2.3)^2)
numericq(val, 1e-3, "\\( e^{(1/2)\\cdot(3 - 2.3)^2} \\)")
```



* Compute the following value:

$$
1 + \frac{1}{2} + \frac{1}{2\cdot 3} + \frac{1}{2\cdot 3\cdot4} + \frac{1}{2\cdot 3\cdot4\cdot5}
$$

```
```

```
val = sum([1/factorial(i) for i in 1:5])
numericq(val, 1e-3, 
	      "\\(1 + \\frac{1}{2} + \\frac{1}{2\\cdot 3} + \\frac{1}{2\\cdot 3\\cdot4} + \\frac{1}{2\\cdot 3\\cdot4\\cdot5}\\)","\\verb+1 + \frac{1}{2} + \frac{1}{2\cdot 3} + \frac{1}{2\cdot 3\cdot4} + \frac{1}{2\cdot 3\cdot4\cdot5}+")
```


* Compute the following value (`cosd` takes degree arguments, `cos` takes radian values):

$$
\frac{5}{\cos(57^\circ)}  + \frac{8}{\sin(57^\circ)}
$$

```
```



```
val = 5/cosd(57) + 8/sind(57)
numericq(val, 1e-3, "\\( \\frac{5}{\\cos(57^\\circ)}  + \\frac{8}{\\sin(57^\\circ)} \\)")
```



* In mathematics a function is defined not only by a rule but also by
  a _domain_ of possible values. Similarly with `julia`. What kind of
  error does `julia` respond with if you try this command: `sqrt(-1)`?

```
```

```
shortq( "DomainError", "What kind of error of `sqrt(-1)`?")
```

## Precedence

* There are 5 operations in the following expression. Write a similar
  expression using 4 pairs of parentheses that evaluates to the same
  value:

$$
1 - 2 + 3 \cdot 4 ^ 5 / 6
$$

```
```

```
shortq("(1 - 2) + ((3 * (4 ^ 5)) / 6)", 
	     "\\( 1 - 2 + 3 * 4 ^ 5 / 6 \\)",
	      "\\( (1 - 2) + ((3 * (4 ^ 5)) / 6) \\)")
```


* Which of these will also produce $1/(3\cdot4)$:


1) `1/3*4`

2) `1/3/4`

3) `1*3/4`

```
```

```
choices = ["\\verb+1/3*4+",
	   "\\verb+1/3/4+",
	   "\\verb+1*3/4+"] 
ans=2
radioq(choices, ans, "\\verb+1/(3\cdot4)+")
```

## Variable

* Let `x=4` and `y=7` compute

$$
x - \sin(x + y)/\cos(x - y)
$$

```
```

```
x = 4
y = 7
val = x - sin(x + y)/ cos(x - y)
numericq(val, 1e-3, "x - sin(x + y)/ cos(x - y)")
```


* For the polynomial

$$
y = ax^2 + bx + c
$$

Let $a=0.00014$, $b=0.61$, $c=649$, and $x=200$. What is $y$?

```
```

```
a=0.00014
b=0.61
c=649
x=200
val = a*x^2 + b*x + c
numericq(val, 1e-4, "ax^2 + bx + c")
```

* If 

$$
\frac{\sin(\theta_1)}{v_1} = \frac{\sin(\theta_2)}{v_2}
$$

and $\theta_1 = \pi/5$, $\theta_2 = \pi/6$, and $v_1=2$, find $v_2$.

```
```

```
t1 = pi/5
t2 = pi/6
v1 = 2
val = sin(t2)/sin(t1)*v1
numericq(val, 1e-4, "find \\(v_2\\)")
```


## Some applications

* The period of simple pendulum depends on a gravitational constant
  $g=9.8$ and the pendulum length, $L$, in meters, according to the formula:
  $T=2\pi\sqrt{L/g}$.

  A rope swing is timed to have a period of $6$ seconds. How long is
  the length of the rope if the formula applies?

```
```

```
g = 9.8
T = 6
L = (T/(2pi))^2*g
val = L
numericq(val, 1e-4, "Find L")
```

* An object dropped from a building of height $h$ (in feet) will fall
  according to the laws of projectile motion:

$$
y(t) = h - 16t^2
$$


If $h=50$ find $y$ if $t=1.5$.

```
```

```
h = 50
t = 1.5
val = h - 16*t^2
numericq(val, 1e-4, "find y")
```

* Suppose $v = 2\cdot 10^8$ and $c = 3 \cdot 10^8$ compute

$$
\frac{1}{\sqrt{1 - v^2/c^2}}
$$

(Be careful, this expression from a theory of relativity is
susceptible to *integer* overflow on some computers!)

```
```

```
v = 2e8
c = 3e8
val = 1/sqrt(1 - v^2/c^2)
numericq(val, 1e-4, "\\( \\frac{1}{\\sqrt{1 - v^2/c^2}} \\)")
```

## Trig practice

* A triangle has sides $a=500$, $b=750$ and $c=901$. Is this a right triangle?

```
```

```
a,b,c = 500, 750, 901
booleanq(c^2 - a^2 - b^2 == 0, "is this a right triangle?")
```

* The law of sines states for a triangle with angle $A$, $B$, and $C$
and opposite sides labeled $a$, $b$, $c$ one has 

$$ 
\sin(A)/a = \sin(B)/b = \sin(C)/c.
$$

If $A=115^\circ$, $a=123$, and $b=16$, find $B$ (in degrees).

```
```

```
A = 115
a = 123
b = 16
sinB = b * sind(A)/a
B = asind(sinB)
val = B
numericq(val, 1e-4, "find B")
```

* The law of cosines generalizes Pythagorean's theorem: $c^2 = a^2 +
  b^2 - 2ab \cos(C)$. A triangle has sides $a=5$, $b=9$, and
  $c=8$. Find the angle $C$.

```
```


```
a = 5
b = 9
c = 8
cosC = (c^2 - a^2 - b^2) / (- 2a*b)
val = acos(cosC)
numericq(val, 1e-4, "find C")
```


## Numbers

Scientific notation represents real numbers as $a \cdot 10^b$, where
$b$ is an integer, and $a$ may be a real number in the range $-1$ to
$1$. In `julia` such numbers are represented with an `e` to replace
the 10, as with `1.2e3` which would be $1.2 \cdot 10^3$ (1,230) or
`3.2e-1`, which would be $3.2 \cdot 10^{-1}$ (0.32).


* What is the sum of `12e3` and `32e-1`?

```
```

```
a = 12e3
b = 32e-1
numericq(a + b)
```


* The output of `sin(pi)` in `julia` gives `1.2246467991473532e-16`. Is this number

```
```

```
choices = ["close to 1.22", "close to -1.22", "close to 0"]
ans = 3
radioq(choices, ans)
```


*  Is `7e-10`  greater than `8e-9`?

```
```

```
booleanq(7e-10 > 8e-9, "Is 7e-10 greater 8e-9?")
```


Julia has different storage type for integers (which are stored
exactly, but have smaller bounds on their size); rational numbers
(which are stored exactly in terms of a numerator and a denominator);
real numbers (which are _approximated_ by floating point numbers); and
complex numbers (which may have either have integer or floating point
values for the two components.) When `julia` parses a value, it will
determine the type by how it is entered.

* For example, the values `2`, `2.0`, `2 + 0im` and `2//1` are all the same and yet all different. What type is each?

```
```

```
longq("The values 2, 2.0, 2 + 0im and 2//1 are all the same and yet all different. How so?", "different storage types")
```



* Compute 

$$
2^{-1}.
$$

(This isn't quite as easy as it looks, as the output of the power
function (`^`) depends on the type of the input variable.)

What command did you use:

```
```

```
longq("Compute `2^(-1)`", "either `1/2`, `1/2^1`, `2.0^(-1)`, ..., but not `2^(-1)`")
```

That's all folks ...
