This is a sample marked up project asa mustache template.

Working idea:

* we have project.mmd and a project.jl file. 
* The project.jl file defines variables to insert in project.mmd
* project.mmd -> project.md (via render(Mustache.template_from_file("p1.mmd")) wihtin project.jl)
* project.md -> project.ipynb and project.tex via process.jl route.

This randomizes the values each semester.

# project on testing

This is a test

* what is a question

For the polynomial ${{a1}}x^2 + {{b1}}x + {{c1}}$ find the smallest root.

```julia
using Rootsb
f(x) = {{a1}}*x^2 + {{b1}}*x + {{c1}}
val = minimum(roots(f))
numericq(val, 1e-3, "smallest root of {{a1}}x^2 + {{b1}}x + {{c1}}")
```

* Another question

Let `f(x) = {{a2}}x^2 - {{b2}}x + {{c2}}`. You can tell that this opens upward because of which coefficient?

```julia
vals = [{{a2}}, {{b2}}, {{c2}}]
ans = 1
radioq(vals, ans, "Which coefficient means it opens up?")
```
